PathsAndQuestionsExample/Models/ErrorViewModel.cs
namespace UploadExample.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PathsAndQuestionsExample/ViewModels/UploadVM.cs
using System.ComponentModel.DataAnnotations;

namespace UploadExample.ViewModels
{
    public class UploadVM
    {
        [Required(ErrorMessage = "Veuillez entrer un nom de fichier")]
        [Display(Name = "Nom du fichier")]
        [StringLength(100)]
        public string FileName { get; set; } = default!;

        [Required(ErrorMessage = "Veuillez choisir un fichier")]
        [Display(Name = "Fichier à téléverser")]
        public IFormFile CustomFile { get; set; } = default!;
    }
}

PathsAndQuestionsExample/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using UploadExample.Models;
using UploadExample.ViewModels;

namespace UploadExample.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Upload(UploadVM vm)
        {
            string folder = Path.Combine(Directory.GetCurrentDirectory(), "Upload");
            //string folder = Path.Combine(HttpContext.Request.Host.Value, "Upload");
            string uniqueFileName = vm.FileName;
            string filePath = Path.Combine(folder, uniqueFileName);
            using var fileStream = new FileStream(filePath, FileMode.Create);
            vm.CustomFile.CopyTo(fileStream);

            return Ok();
        }
    }
}

PathsAndQuestionsExample/Controllers/JsonController.cs
using Microsoft.AspNetCore.Mvc;

namespace UploadExample.Controllers
{
    public class JsonController : Controller
    {
        public JsonResult FetchData()
        {
            return Json(new { Name = "Chuck", Age = -1, Date = DateTime.Now.ToString("yyyy-MM-dd HH:mm:SS") });
        }
    }
}

PathsAndQuestionsExample/Controllers/OtherController.cs
using Microsoft.AspNetCore.Mvc;

namespace UploadExample.Controllers
{
    public class OtherController : Controller
    {
        public IActionResult IndexOther()
        {
            return View();
        }
    }
}

PathsAndQuestionsExample/Views/Home/Index.cshtml
@model UploadVM
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <img src="~/logo.png" width="100" /> <!-- ** WORKING LOCALLY AND ONCE DEPLOYED ** -->
    <img src="./logo.png" width="100" /> <!-- WORKING LOCALLY BUT NOT ONCE DEPLOYED -->
    <img src="./~/logo.png" width="100" /> <!-- NOT WORKING LOCALLY AND ONCE DEPLOYED -->
    <img src="/logo.png" width="100" /> <!-- WORKING LOCALLY BUT NOT ONCE DEPLOYED -->
    <img src="logo.png" width="100" /> <!-- WORKING LOCALLY BUT NOT ONCE DEPLOYED -->

    <form enctype="multipart/form-data" asp-action="Upload">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="FileName" class="control-label"></label>
                    <input asp-for="FileName" class="form-control" />
                    <span asp-validation-for="FileName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="CustomFile" class="control-label"></label>
                    <div class="custom-file">
                        <input asp-for="CustomFile" class="custom-file-input" id="customFile">
                        <label class="custom-file-label" for="customFile">Choisir le fichier</label>
                    </div>
                    <span asp-validation-for="CustomFile" class="text-danger"></span>
                </div>
            </div>
        </div>
        @*  <div class="form-group">
        <label asp-for="FileName" class="control-label"></label>
        <textarea asp-for="FileName" class="form-control"></textarea>
        <span asp-validation-for="FileName" class="text-danger"></span>
        </div> *@
        <div class="form-group">
            <input type="submit" value="Enregistrer" class="btn btn-sm btn-info rounded-0 text-uppercase" />
        </div>

    </form>
</div>

PathsAndQuestionsExample/Views/Other/IndexOther.cshtml
@model UploadVM
@{
    ViewData["Title"] = "Other Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to another page</h1>
</div>

PathsAndQuestionsExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
@{
    // string myURL = Context.Request.Host.Value;
    string BASE_URL_RAZOR = Url.Content("~");
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UploadExample</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UploadExample.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UploadExample</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Other" asp-action="IndexOther">Other page</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - UploadExample - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script>
        const BASE_URL = @Json.Serialize(BASE_URL_RAZOR);
        console.log("BASE_URL: " + BASE_URL); // Aller voir dans ~/js/site.js pour une utilisation de fetch avec la valeur.
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>